# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.speedqueue.com
title: SpeedQueue
description: > # "Write an awesome description for your new site here. 
  Les temps d'attente de vos parcs d'attraction favoris.
copyright: 'Copyright &copy; 2015 SpeedQueue. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/speedqueue
  - title: facebook
    url: https://www.facebook.com/app.speedqueue/
